# Generated by Django 2.0 on 2017-12-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('railway', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
    ]
